# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 200
  tensorboard_logdir: tb
  wandb_project: wandb

checkpoint:
  save_interval_updates: 25000
  keep_interval_updates: 1
  no_epoch_checkpoints: true

task:
  _name: audio_pretraining
  data: ???
  max_sample_size: 250000
  min_sample_size: 32000
  normalize: false

dataset:
  num_workers: 0
  max_tokens: 1400000
  skip_invalid_size_inputs_valid_test: true

distributed_training:
  distributed_world_size: 8 # use 8 or 16 in pcl

criterion:
  _name: model
  log_keys: 
    - target_var
    - pred_var

optimization:
  max_update: 400000
  lr: [0.004]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-06
  weight_decay: 0.01

lr_scheduler:
  _name: polynomial_decay
  warmup_updates: 25000

model:
  _name: random_projection
  # quantize_targets: true
  # final_dim: 256
  # encoder_layerdrop: 0.05
  # dropout_input: 0.1
  # dropout_features: 0.1
  # feature_grad_mult: 0.1
  # encoder_embed_dim: 768
