# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 200
  tensorboard_logdir: tb
  wandb_project: wandb

checkpoint:
  save_interval_updates: 25000
  keep_interval_updates: 1
  no_epoch_checkpoints: true

task:
  _name: audio_pretraining
  data: ???
  max_sample_size: 250000
  min_sample_size: 32000
  normalize: false

dataset:
  num_workers: 6
  max_tokens: 560000
  skip_invalid_size_inputs_valid_test: true

distributed_training:
  distributed_world_size: 1 # use 8 or 16 in pcl
  ddp_backend: legacy_ddp

criterion:
  _name: model
  log_keys: 
    - target_var
    - pred_var

optimization:
  max_update: 400000
  lr: [0.004]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-06
  weight_decay: 0.01

lr_scheduler:
  _name: polynomial_decay
  warmup_updates: 25000

model:
  _name: random_projection
  xavier_type: normal
  codebook_vocab_size: 8192
  codebook_dim: 16
  conv_feature_layers: '[(512, 10, 5)] + [(512, 3, 2)] * 4 + [(512,2,2)] + [(512,2,2)]'
  encoder_embed_dim: 1024
  encoder_ffn_embed_dim: 4096 # according to conformer paper
  dropout_ratio: 0.0
  encoder_layers: 24 # encoder layers of conformer
  encoder_depthwise_conv_kernel_size: 5
  encoder_attention_heads: 8
  mask_length: 20
  mask_prob: 0.1
  
